require('datatables.net');
require('datatables.net-bs4/js/dataTables.bootstrap4.min.js');
require('datatables.net-buttons');
require('datatables.net-buttons/js/buttons.colVis.min.js');
require('datatables.net-buttons/js/buttons.html5.min.js');
require('datatables.net-buttons/js/buttons.print.min.js');
require('datatables.net-buttons/js/buttons.flash.min.js');
require('datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js');
require('datatables.net-fixedheader/js/dataTables.fixedHeader.min.js');
